export const currenciesContent = [
  { value: "$", label: "US Dollar" },
  { value: "€", label: "Euro" },
  { value: "£", label: "British Pound" },
  { value: "₣", label: "Swiss Franc" },
  { value: "kr", label: "Krona" },
  { value: "zł", label: "Polish Złoty" },
  { value: "¥", label: "Japanese Yen" },
  { value: "₪", label: "Israeli New Shekel" },
  { value: "₺", label: "Turkish Lira" },
  { value: "R$", label: "Brazilian Real" },
  { value: "Mex$", label: "Mexican Peso" },
  { value: "₽", label: "Russian Ruble" },
  { value: "₩", label: "South Korean Won" },
  { value: "S$", label: "Singapore Dollar" },
  { value: "₹;", label: "Indian Rupee" },
  { value: "R", label: "South African Rand" },
  { value: "CN¥", label: "Chinese Yuan" },
  { value: "₴", label: "Ukrainian Hryvnia" },
  { value: "Rp", label: "Indonesian Rupiah" },
  { value: "₫", label: "Vietnamese Đồng" },
  { value: "₦", label: "Nigerian Naira" },
  { value: "₱", label: "Philippine Peso" },
  { value: "HK$", label: "Hong Kong Dollar" },
  { value: "CA$", label: "Canadian Dollar" },
  { value: "A$", label: "Australian Dollar" },
  { value: "NZ$", label: "New Zealand Dollar" },
];
